version: "3.9"
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql_server2019
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Password123